### ISSUE TITLE
Is it possible to use import for fable JSX components?

### ISSUE THREAD

**Issue by halcwb** [alfonsogarciacaro/fable-react-sample#3] opened 2023-03-22 08:48 UTC
Well it is possible, but then you have to hack the generated JSX file.

Example:

```jsx
    JSX.jsx
        $"""
    import {{ ThemeProvider }} from '@mui/material/styles';
    import CssBaseline from '@mui/material/CssBaseline';
    import React from "react";
    import Box from '@mui/material/Box';
    import {{View as Router}} from './Components/Router.jsx';

    <React.StrictMode>
        <ThemeProvider theme={theme}>
            <Box sx={ {| height= "100vh"; overflowY = "hidden" |} }>
                <CssBaseline />
                <Router onUrlChanged={UrlChanged >> dispatch} />
                {
                    Pages.GenPres.View({|
                        patient = state.Patient
                        .... etc
                    |})
                }
            </Box>
        </ThemeProvider>
    </React.StrictMode>
    """
```

I import the router component as a regular js component with an import and then can use the props to pass the dispatch function. The Router component looks like:

```f#
    [<ReactComponent>]
    let View(props: {| onUrlChanged: string list -> unit |}) = 
        React.router [
            router.onUrlChanged props.onUrlChanged
        ]

```

The only problem is the path for the import, this will compile to:
`import { View as Router } from "../src/Client/Components/Router.jsx";` instead of
`import { View as Router } from "../Components/Router.jsx";`

Is there a way to get the path right so fable compiles it correctly.

This would make the JSX code cleaner and even more comparable with regular JSX.

**Comment by alfonsogarciacaro** [comment] 2023-03-22 09:48
This is intended. By design, Fable only moves .fs files to the output directory (same behavior as Typescript) so relative import paths are adjusted when the source files move to the output directory. You have two options:

1. In the F# file, use the relative path to where Router.jsx will be in the output directory and Fable will adjust it:
    `import { View as Router } from "../../../dist/Components/Router.jsx"`

2. Use the `${outDir}` macro that will resolve paths relative to the output directory:
     `import { View as Router } from "${outDir}/Components/Router.jsx"`

**Closed as completed** 2023-03-22 09:58 UTC
